# Generated by Django 5.2.3 on 2025-11-27 23:57

from django.db import migrations
import os
from django.conf import settings

def setup_google_auth(apps, schema_editor):
    # We can't import models directly, we must use apps.get_model
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    # 1. Setup the Site
    # Django creates a site with ID=1 by default ("example.com"). 
    # We update it to be valid for our dev/prod environment.
    site, _ = Site.objects.get_or_create(id=settings.SITE_ID)
    site.domain = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost:8000').split(',')[0]
    site.name = os.environ.get('NAME', 'My Startpage')
    site.save()

    # 2. Setup the Google Social App
    client_id = os.environ.get('GOOGLE_CLIENT_ID')
    secret = os.environ.get('GOOGLE_CLIENT_SECRET')

    if client_id and secret:
        # Get or Create the Google App entry
        google_app, created = SocialApp.objects.get_or_create(
            provider='google',
            defaults={
                'name': 'Google',
                'client_id': client_id,
                'secret': secret,
            }
        )
        
        # If it already existed, update the credentials in case .env changed
        if not created:
            google_app.client_id = client_id
            google_app.secret = secret
            google_app.name = 'Google'
            google_app.save()

        # Link the app to our site
        google_app.sites.add(site)
        print(f"\nSuccessfully configured Google OAuth for site: {site.domain}")
    else:
        print("\nSkipping Google App setup: GOOGLE_CLIENT_ID or GOOGLE_CLIENT_SECRET not found in env.")

class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0001_initial'), # Depend on your last startpages migration
        ('sites', '0002_alter_domain_unique'), # Depend on sites
        ('socialaccount', '0001_initial'), # Depend on allauth socialaccount
    ]

    operations = [
        migrations.RunPython(setup_google_auth),
    ]