# Generated by Django 5.2.3 on 2025-11-27 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0002_startpage_is_default_profile'),
        ('startpages', '0003_setup_google_social_app'),
    ]

    operations = [
    ]
