# Generated by Django 5.2.3 on 2025-11-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0004_merge_20251128_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True),
        ),
    ]
