# Generated by Django 5.2.3 on 2025-11-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0005_link_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NTFY_active', models.BooleanField(default=True, help_text='If active, NTFY notifications are enabled.')),
                ('NTFY_send_registration', models.BooleanField(default=True, help_text='If active, Notifications are sent for all new registrations.')),
                ('DAILY_MAIL_ACTIVE', models.BooleanField(default=True, help_text='If active, daily mails are enabled.')),
                ('DAILY_MAIL_INCLUDE_REGISTRATIONS', models.BooleanField(default=True, help_text='If active, daily mails include registrations.')),
            ],
        ),
    ]
