# Generated by Django 5.2.3 on 2025-11-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0006_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='NTFY_registration_priority',
            field=models.CharField(choices=[('max', 'Max'), ('high', 'High'), ('default', 'Default'), ('low', 'Low'), ('min', 'Min')], default='default', help_text='Priority for registration notifications.', max_length=10),
        ),
    ]
