# Generated by Django 5.2.3 on 2025-11-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0007_globalsettings_ntfy_registration_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='NTFY_registration_priority',
            field=models.CharField(choices=[('max', 'Max'), ('high', 'High'), ('default', 'Default'), ('low', 'Low'), ('min', 'Min')], default='default', help_text='High priorities will make noise while low priorities are silent notifications.', max_length=10),
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_dark', models.BooleanField(default=False, help_text='Does this theme use dark mode?')),
                ('preview_colors', models.JSONField(default=list, help_text='List of 4 hex codes for the UI preview')),
                ('css_variables', models.JSONField(default=dict, help_text='Dictionary mapping CSS variable names to values')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='startpages.globalsettings')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='startpages.colorscheme'),
        ),
    ]
