# Generated by Django 5.2.3 on 2025-11-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0008_alter_globalsettings_ntfy_registration_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorscheme',
            name='preview_colors',
        ),
    ]
