# Generated by Django 5.2.3 on 2025-11-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0009_remove_colorscheme_preview_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorscheme',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='order',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers appear first'),
        ),
    ]
