# Generated by Django 5.2.3 on 2026-07-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0010_alter_colorscheme_options_colorscheme_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('glass', 'Glass'), ('minimal', 'Minimal'), ('elevated', 'Elevated')], default='solid', help_text='Visual style of the section cards on startpages.', max_length=20),
        ),
    ]
