# Generated by Django 5.2.3 on 2026-07-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpages', '0011_profile_card_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_style',
            field=models.CharField(choices=[('solid', 'Solid'), ('glass', 'Glass'), ('minimal', 'Minimal'), ('elevated', 'Elevated'), ('dual', 'Dual-tone')], default='solid', help_text='Visual style of the section cards on startpages.', max_length=20),
        ),
    ]
